import assert from 'node:assert/strict';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { Store } from '../src/db.js';
import { createServer } from '../src/server.js';

test('API enforces bearer token and records a click', async () => {
  const store=new Store(join(mkdtempSync(join(tmpdir(),'speed-dial-api-test-')), 'bookmarks.sqlite'));
  const app=createServer({store,token:'test-token'});
  assert.equal((await app.inject('/health')).statusCode, 200);
  assert.equal((await app.inject('/api/folders')).statusCode, 401);
  const headers={authorization:'Bearer test-token'};
  const folder=await app.inject({method:'POST',url:'/api/folders',headers,payload:{name:'Reading'}});
  assert.equal(folder.statusCode,201);
  const folderId=(folder.json() as {id:string}).id;
  const automaticFolder=await app.inject({method:'POST',url:'/api/folders',headers,payload:{name:'GitHub',autoRules:['*.github.com']}});
  assert.equal(automaticFolder.statusCode,201);
  const automaticFolderId=(automaticFolder.json() as {id:string}).id;
  const link=await app.inject({method:'POST',url:`/api/folders/${folderId}/links`,headers,payload:{url:'http://127.0.0.1/metadata',title:'Manual title',description:'Manual description'}});
  assert.equal(link.statusCode,201);
  assert.equal((link.json() as {metadataStatus:string}).metadataStatus,'pending');
  assert.equal((link.json() as {title:string}).title,'Manual title');
  assert.equal((link.json() as {description:string}).description,'Manual description');
  const normalizedUrl=await app.inject({method:'POST',url:`/api/folders/${folderId}/links`,headers,payload:{url:'example.com'}});
  assert.equal(normalizedUrl.statusCode,201);
  assert.equal((normalizedUrl.json() as {url:string}).url,'https://example.com');
  const collected=await app.inject({method:'POST',url:`/api/folders/${folderId}/links`,headers,payload:{url:'https://gist.github.com/example'}});
  assert.equal(collected.statusCode,201);
  assert.equal((collected.json() as {folderId:string}).folderId,automaticFolderId);
  const duplicate=await app.inject({method:'GET',url:'/api/links/duplicates?url=example.com',headers});
  assert.equal(duplicate.statusCode,200);
  assert.equal((duplicate.json() as Array<{url:string}>)[0]?.url,'https://example.com');
  const linkId=(link.json() as {id:string}).id;
  const clicked=await app.inject({method:'POST',url:`/api/links/${linkId}/clicks`,headers});
  assert.equal(clicked.statusCode,200);
  assert.equal((clicked.json() as {clickCount:number}).clickCount,1);
  const recommendations=await app.inject({method:'GET',url:'/api/recommendations',headers});
  assert.equal(recommendations.statusCode,200);
  assert.equal((recommendations.json() as {recommendations:Array<{id:string;score:number}>}).recommendations[0]?.id,linkId);
  assert.equal((recommendations.json() as {recommendations:Array<{score:number}>}).recommendations[0]?.score > 0, true);
  const history=await app.inject({method:'POST',url:'/api/history/records',headers,payload:{records:[{url:'https://example.com/article',title:'Example article',lastVisitTime:1_700_000_000_000,visitCount:3,source:'initial'},{url:'https://example.com/article',title:'Updated title',lastVisitTime:1_700_000_001_000,visitCount:4,source:'live'}]}});
  assert.equal(history.statusCode,200);
  assert.equal(history.json().received,2);
  const removed=await app.inject({method:'POST',url:'/api/history/removals',headers,payload:{allHistory:false,urls:['https://example.com/article']}});
  assert.equal(removed.statusCode,200);
  assert.equal(removed.json().marked,1);
  assert.equal((store.db.prepare('SELECT chrome_removed_at FROM browser_history_pages WHERE url=?').get('https://example.com/article') as {chrome_removed_at:string | null}).chrome_removed_at !== null, true);
  const historyList=await app.inject({method:'GET',url:'/api/history?query=updated&limit=50',headers});
  assert.equal(historyList.statusCode,200);
  assert.equal((historyList.json() as {items:Array<{url:string}>}).items[0]?.url,'https://example.com/article');
  const internal=await app.inject({method:'POST',url:`/api/folders/${folderId}/links`,headers,payload:{url:'chrome://extensions/',title:'扩展管理'}});
  assert.equal(internal.statusCode,201);
  assert.equal((internal.json() as {metadataStatus:string}).metadataStatus,'succeeded');
  assert.equal((internal.json() as {title:string}).title,'扩展管理');
  const aiImport=await app.inject({method:'POST',url:'/api/ai/links',headers,payload:{links:[
    {url:'ai.example.com',title:'AI added',folderName:'AI 收集'},
    {url:'https://ai.example.com',description:'Updated by agent',folderName:'已整理'},
    {url:'chrome://bookmarks/',title:'Chrome bookmarks'}
  ],onDuplicate:'update'}});
  assert.equal(aiImport.statusCode,201);
  assert.equal(aiImport.json().created.length,2);
  assert.equal(aiImport.json().updated.length,1);
  assert.equal(aiImport.json().foldersCreated.length,3);
  const aiLink=(aiImport.json() as {updated:Array<{url:string;description:string;folderId:string}>}).updated[0];
  assert.equal(aiLink.url,'https://ai.example.com');
  assert.equal(aiLink.description,'Updated by agent');
  const aiRetry=await app.inject({method:'POST',url:'/api/ai/links',headers,payload:{links:[{url:'ai.example.com'}]}});
  assert.equal(aiRetry.statusCode,201);
  assert.equal(aiRetry.json().skipped.length,1);
  assert.equal(aiRetry.json().skipped[0].url,'https://ai.example.com');
  const libraryExport=await app.inject({method:'GET',url:'/api/export',headers});
  assert.equal(libraryExport.statusCode,200);
  assert.equal(libraryExport.json().format,'local-speed-dial/bookmarks');
  assert.equal(libraryExport.json().scope,'library');
  assert.equal('updatedAt' in libraryExport.json().settings,false);
  const aiFolder=(aiImport.json() as {foldersCreated:Array<{id:string;name:string}>}).foldersCreated.find(folder => folder.name === '已整理')!;
  const folderExport=await app.inject({method:'GET',url:`/api/folders/${aiFolder.id}/export`,headers});
  assert.equal(folderExport.statusCode,200);
  assert.equal(folderExport.json().scope,'folder');
  assert.equal(folderExport.json().folders.length,1);
  assert.equal(folderExport.json().folders[0].links[0].url,'https://ai.example.com');
  const restoreStore=new Store(join(mkdtempSync(join(tmpdir(),'speed-dial-import-test-')), 'bookmarks.sqlite'));
  const restoreApp=createServer({store:restoreStore,token:'test-token'});
  const imported=await restoreApp.inject({method:'POST',url:'/api/import',headers,payload:{bundle:libraryExport.json(),onDuplicate:'skip'}});
  assert.equal(imported.statusCode,201);
  assert.equal(imported.json().created.length,libraryExport.json().folders.reduce((total:number, folder:{links:unknown[]}) => total + folder.links.length, 0));
  assert.equal(imported.json().foldersCreated.length,libraryExport.json().folders.length);
  const intoExisting=await restoreApp.inject({method:'POST',url:'/api/import',headers,payload:{bundle:folderExport.json(),targetFolderId:imported.json().foldersCreated[0].id,onDuplicate:'update'}});
  assert.equal(intoExisting.statusCode,201);
  assert.equal(intoExisting.json().updated.length,1);
  await restoreApp.close();
  await app.close();
});
